### PR TITLE
Audrey Bertin Challenge 3 – Pivot

### PR DESCRIPTION
**Pull request by ambertin**
Also includes commits made on the upstream repository to remove template files from the `posts` folder

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
posts/_data/organiceggpoultry.xls seems modify. Did you change anything from that?

**Comment by ambertin** [comment]
I didn't make any changes that I know of. I think I opened it once though. Maybe I opened it and clicked on something and when I saved, it slightly modified

**Comment by ambertin** [comment]
I think I fixed it and it's gone from the pull request now. Still not sure why it was there the first time

**Review by SidharthSaluja — APPROVED** [review]
You are expert in Github

**Pull request merged**
