### PR TITLE
Challenge 2 Gabrielle Roman

### PR DESCRIPTION
**Pull request by GabrRoman**
Character data issues.

### CODE REVIEW

**Comment by SidharthSaluja** [comment]
This is Sidharth's bot - Please render your challenge qmd file in post folder to generate freeze files

**Review by SidharthSaluja — COMMENTED** [review]
Hiting render button should worked. Anyways we would see this in the meeting

**Review by SidharthSaluja — APPROVED** [review]
Okay it works. Do we still need meeting??

**Comment by GabrRoman** [comment]
I think I'll cancel for the time being, thank you!

**Pull request merged**
