### PR TITLE
Final Solution to Challenge 1

### PR DESCRIPTION
**Pull request by moirachiong**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Can you delete posts/DACSS 601 Summer 1 Challenge 2_Moira Chiong.R
Also can you move posts/About Me_Moira Chiong.qmd to about folder and follow the structure of _templates/AboutTemplate.qmd. Your structure of About Me_Moira Chiong.qmd seems wrong. I would say rename your About Me_Moira Chiong.qmd  to 
About Me_Moira_Chiong.qmd so that file name doesnt have space between then (currently Moira and Chiong have space). 

Please schedule a meeting when in trouble

**Comment by moirachiong** [comment]
Got it, will do!

Thanks,
Moira

**Review by SidharthSaluja — COMMENTED** [review]
Could of corrections
1. Delete posts/About Me_Moira Chiong.qmd
2. Delete posts/DACSS 601 Summer 1 Challenge 2_Moira Chiong.R
3. Your challenge 2 is still wrong. I cant see yaml header (--- lines). Fix it and render again and send me
4. Rename about/images/Moira Profile Pic.png to about/images/Moira_Profile_Pic.png (because file name shouldn’t have spaces)

**Comment by moirachiong** [comment]
Could of corrections

Delete posts/About Me_Moira Chiong.qmd--- DONE
Delete posts/DACSS 601 Summer 1 Challenge 2_Moira Chiong.R---DONE
Your challenge 2 is still wrong. I cant see yaml header (--- lines). Fix it and render again and send me--SUBMITTED AGAIN
Rename about/images/Moira Profile Pic.png to about/images/Moira_Profile_Pic.png (because file name shouldn’t have spaces)--DONE

**Review by SidharthSaluja — COMMENTED** [review]
Nope I dont see anything changed. Did you push to GitHub?

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
