### PR TITLE
Final_Project

### PR DESCRIPTION
**Pull request by LeoLin990405**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
You sure you wanna delete hw3??

**Comment by LeoLin990405** [comment]
I've uploaded my HW3 to the course repo before, but this HW3 file was accidentally uploaded by my git bug yesterday

**Review by SidharthSaluja — COMMENTED** [review]
Umm I checked ur repo of GitHub. It feels to me if you delete this hw3, it will get removed from courseblog also. So please be sure about that

**Comment by LeoLin990405** [comment]
I see, so am I closing the request first to avoid deleting my HW3 file now?

**Comment by SidharthSaluja** [comment]
Ok

**Pull request closed without merging**
