### PR TITLE
Add Noah Dixon challenge 1 solution

### PR DESCRIPTION
**Pull request by noahdixon**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Sync the fork

**Comment by noahdixon** [comment]
> Sync the fork

All set I think. Thank you!

**Review by SidharthSaluja — COMMENTED** [review]
1. Remove freeze folder entirely
2. Render the posts/challenge1_noahdixon.qmd to generate new freeze
3. commit .qmd and corresponding freeze

Follow these steps and you would be all set

**Comment by noahdixon** [comment]
> 1. Remove freeze folder entirely
> 2. Render the posts/challenge1_noahdixon.qmd to generate new freeze
> 3. commit .qmd and corresponding freeze
> 
> Follow these steps and you would be all set

I did these steps and made a new commit "Regenerate freeze folder for challenge 1". Is it okay now? Thanks for the help.

**Review by SidharthSaluja — APPROVED** [review]
Awsome

**Pull request merged**
